HH/Controllers/FormSubmitController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Http;
using HH.Core.Models;
using HH.Extensions;
using HH.Models;
using HHCore.Models;
using Microsoft.AspNet.Identity;

namespace HH.Controllers
{
    public class FormSubmitController : ApiController
    {

        pmacarth_HygieneEntities db = new pmacarth_HygieneEntities();

        [Route("api/Floors/")]
        [Authorize]
        [HttpGet]
        public IHttpActionResult GetFloors()
        {
            var floors = db.Floors.Select(f => new FloorModel
            {
                FloorId = f.FloorId.ToInt(),
                Name = f.Name
            });

            return Ok(floors.ToList());
        }

        [Route("api/HCW/")]
        [Authorize]
        [HttpGet]
        public IHttpActionResult GetHCWPositions()
        {
            var positions = db.HCWs.Select(f => new HCWModel()
            {
                HCWId = f.HCWId.ToInt(),
                Name = f.Name
            });

            return Ok(positions.ToList());
        }

        [Route("api/Opportunities/")]
        [Authorize]
        [HttpGet]
        public IHttpActionResult GetOpportunities()
        {
            var positions = db.Opportunities.Select(f => new OpportunityModel()
            {
                OpportunityId = f.OpportunityId.ToInt(),
                Name = f.Name
            });

            return Ok(positions.ToList());
        }

        [Route("api/HHCT/")]
        [Authorize]
        [HttpGet]
        public IHttpActionResult GetHygieneCompliance()
        {
            var positions = db.HandHygieneComplianceTypes.Select(f => new HandComplianceModel()
            {
                ComplianceId = f.HandHygieneComplianceTypeId.ToInt(),
                Name = f.Name
            });

            return Ok(positions.ToList());
        }

        [Route("api/AllLists/")]
        [Authorize]
        [HttpGet]
        public IHttpActionResult GetAll()
        {
            var compliaces = db.HandHygieneComplianceTypes.Select(f => new HandComplianceModel()
            {
                ComplianceId = (int)(f.HandHygieneComplianceTypeId),
                Name = f.Name
            }).ToList();

            var floors = db.Floors.Select(f => new FloorModel
            {
                FloorId = (int)(f.FloorId),
                Name = f.Name
            }).ToList();


            var hcws = db.HCWs.Select(f => new HCWModel()
            {
                HCWId = (int)(f.HCWId),
                Name = f.Name
            }).ToList();

            var opportunites = db.Opportunities.Select(f => new OpportunityModel()
            {
                OpportunityId = (int)(f.OpportunityId),
                Name = f.Name
            }).ToList();

            return Ok(new ObservationModel()
            {
                HandCompliance = compliaces,
                Floors = floors,
                Hcws = hcws,
                Opportunities = opportunites
            });
        }

        [Route("api/SubmitObservation/")]
        [Authorize]
        [HttpPost]
        public IHttpActionResult SubmitObservation(ObservationViewModel model)
        {
            var floor = db.Floors.FirstOrDefault(f => (int)f.FloorId == model.SelectedFloor.FloorId);
            var HHC = db.HandHygieneComplianceTypes.FirstOrDefault(f => (int)f.HandHygieneComplianceTypeId == model.SelectedHHC.ComplianceId);
            var op = db.Opportunities.FirstOrDefault(f => (int)f.OpportunityId == model.SelectedOpportunity.OpportunityId);
            var hcw = db.HCWs.FirstOrDefault(f => (int)f.HCWId == model.SelectedHCW.HCWId);
            var user = db.AspNetUsers.FirstOrDefault(f => f.Id == model.UserId);


            var observation = new Observation()
            {
                DateSubmitted = model.SubmitDate,
                Floor = floor,
                HandHygieneComplianceType = HHC,
                Opportunity = op,
                HCW = hcw,
                User = user,
                FacilityName = model.FacilityName,
                IsGloveCompliant = model.IsGlovesCompliant,
                IsGownCompliant = model.IsGownCompliant,
                IsMaskCompliant = model.IsMaskCompliant,
                IsRespiratorCompliant = model.IsRespiratorCompliant,
                IsBrownBleachCompliant = model.IsBrownBleachCompliant,
                Note = model.Note
            };

            db.Observations.Add(observation);
            db.SaveChanges();

            return Ok();
        }

        [Route("FormSubmit/SubmitObservation")]
        [Authorize]
        [HttpPost]
        public IHttpActionResult SubmitObservationFromWeb(ObservationViewModel model)
        {
            var floor = db.Floors.FirstOrDefault(f => (int)f.FloorId == model.SelectedFloor.FloorId);
            var HHC = db.HandHygieneComplianceTypes.FirstOrDefault(f => (int)f.HandHygieneComplianceTypeId == model.SelectedHHC.ComplianceId);
            var op = db.Opportunities.FirstOrDefault(f => (int)f.OpportunityId == model.SelectedOpportunity.OpportunityId);
            var hcw = db.HCWs.FirstOrDefault(f => (int)f.HCWId == model.SelectedHCW.HCWId);
            var userId = HttpContext.Current.User.Identity.GetUserId();
            var user = db.AspNetUsers.FirstOrDefault(f => f.Id == userId);


            var observation = new Observation()
            {
                DateSubmitted = model.SubmitDate,
                Floor = floor,
                HandHygieneComplianceType = HHC,
                Opportunity = op,
                HCW = hcw,
                User = user,
                FacilityName = model.FacilityName,
                IsGloveCompliant = model.IsGlovesCompliant,
                IsGownCompliant = model.IsGownCompliant,
                IsMaskCompliant = model.IsMaskCompliant,
                IsRespiratorCompliant = model.IsRespiratorCompliant,
                IsBrownBleachCompliant = model.IsBrownBleachCompliant,
                Note = model.Note
            };

            db.Observations.Add(observation);
            db.SaveChanges();

            return Ok();
        }

    }
}

HH/Controllers/HomeController.cs
using HH.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HH.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            if (!User.Identity.IsAuthenticated)
            {
                return RedirectToAction("Login", "Account");
            }
            return View();
        }
        public ActionResult Retrieval()
        {
            if (!User.Identity.IsAuthenticated)
            {
                return RedirectToAction("Login", "Account");
            }
            return View();
        }

        public ActionResult Create()
        {
            if (!User.Identity.IsAuthenticated)
            {
                return RedirectToAction("Login", "Account");
            }
            return View(new ObservationEntryViewModel()
            {
                SubmitDate = DateTime.Now
            });
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

HH/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

HH/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

HH/Views/Home/Create.cshtml
@{
    ViewBag.Title = "Home Page";
}
@model HH.Models.ObservationEntryViewModel
<div class="pull-right">
    @using (Html.BeginForm("LogOff", "Account", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
    {
        @Html.AntiForgeryToken()

        <input value="LogOff" type="submit" />
    }
</div>
<div class="jumbotron">
    <h1>Hygiene Tracker</h1>
</div>
@using (Html.BeginForm("SubmitObservation", "FormSubmit", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    <div class="row">
        <div class="col-lg-4">
            <div class="form-group">
                @Html.LabelFor(x => x.SelectedFloor, "Floor")
                @Html.EnumDropDownListFor(x => x.SelectedFloor, "Select a floor", new { @class = "form-control" })
            </div>
        </div>
        <div class="col-lg-4">
            <div class="form-group">
                @Html.LabelFor(x => x.SelectedHCW, "Worker Type")
                @Html.EnumDropDownListFor(x => x.SelectedHCW, "Select a Health Care Worker", new { @class = "form-control" })
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-4">
            <div class="form-group">
                @Html.LabelFor(x => x.SelectedOpportunity, "Opportunity")
                @Html.EnumDropDownListFor(x => x.SelectedOpportunity, "Select an opportunity", new { @class = "form-control" })
            </div>
        </div>
        <div class="col-lg-4">
            <div class="form-group">
                @Html.LabelFor(x => x.SelectedHHC, "Compliance type")
                @Html.EnumDropDownListFor(x => x.SelectedHHC, "Select a hand hygiene compliance", new { @class = "form-control" })
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-4">
            <div class="form-group">
                <section id="DateRangeForm">
                    <Label>Submit Date:</Label>
                    @Html.TextBoxFor(f => f.SubmitDate, new { @name = "SubmitDateInput", @id = "SubmitDateInput" })
                    <div id="SubmitDateCal" class="date-picker"></div>
                </section>
            </div>
        </div>
        <div class="col-lg-4">
            <div class="form-group">
                <label>Isolation Type</label>
                <div>
                    @Html.DropDownListFor(m => m.IsolationType, Model.IsolationTypes, new { @id = "IsolationType", @class = "form-control" })
                </div>
            </div>
            <div class="form-group">
                <div class="contact browncontact droplet">
                    @Html.LabelFor(m => m.IsGownCompliant, "Gown:")
                    @Html.EditorFor(m => m.IsGownCompliant)
                </div>
                <div class="contact browncontact droplet">
                    @Html.LabelFor(m => m.IsGlovesCompliant, "Gloves:")
                    @Html.EditorFor(m => m.IsGlovesCompliant)
                </div>
                <div class="browncontact">
                    @Html.LabelFor(m => m.IsBrownBleachCompliant, "Bleach:")
                    @Html.EditorFor(m => m.IsBrownBleachCompliant)
                </div>
                <div class="droplet">
                    @Html.LabelFor(m => m.IsMaskCompliant, "Mask:")
                    @Html.EditorFor(m => m.IsMaskCompliant)
                </div>
            </div>
            <div class="form-group">
                <div class="airborne">
                    @Html.LabelFor(m=>m.AirborneDropItems, "Airborne")
                    @Html.DropDownList("AirborneDrop", Model.AirborneDropItems, new {@class = "form-control"})
                </div>
            </div>
            <div class="form-group">
                <div id="respCheckbox">
                    @Html.LabelFor(m=>m.IsRespiratorCompliant, "Respirator:")
                    @Html.EditorFor(m => m.IsRespiratorCompliant)
                </div>
            </div>
        </div>
    </div>
    <button type="submit">Submit</button>
}

HH/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}
@using HH.Models
@model ObservationRangeViewModel
<div class="pull-right">
    @using (Html.BeginForm("LogOff", "Account", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
    {
        @Html.AntiForgeryToken()

        <input value="LogOff" type="submit"/>
    }
</div>
<div class="jumbotron">
    <h1>Hygiene Tracker</h1>
</div>
@using (Html.BeginForm("GetByDateRange", "Observations", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    <div class="row">
        <div class="col-md-6">
            <a href="@Url.Action("Retrieval")" class="btn btn-lg btn-primary">
                    Generate Report
            </a>
        </div>
        <div class="col-md-6">
            <a href="@Url.Action("Create")" class="btn btn-lg btn-primary">
                New Observation
            </a>
        </div>
    </div>

}

HH/Views/Home/Retrieval.cshtml
@{
    ViewBag.Title = "Home Page";
}
@using HH.Models
@model ObservationRangeViewModel
<div class="pull-right">
    @using (Html.BeginForm("LogOff", "Account", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
    {
        @Html.AntiForgeryToken()

        <input value="LogOff" type="submit" />
    }
</div>
<div class="jumbotron">
    <h1>Hygiene Tracker</h1>
</div>
@using (Html.BeginForm("GetByDateRange", "Observations", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    <div class="row">
        <div class="col-md-6">
            <section id="DateRangeForm">
                <Label>Starting Date:</Label>
                @Html.TextBoxFor(f => f.StartDate, new { @name = "StartDateInput", @id = "StartDateInput" })
                <div id="StartDate" class="date-picker"></div>
            </section>
        </div>
        <div class="col-md-6">
            <section id="DateRangeForm">
                <Label>Ending Date:</Label>
                @Html.TextBoxFor(f => f.EndDate, new { @class = "date-picker", @name = "EndDateInput", @id = "EndDateInput" })
                <div id="EndDate" class="date-picker"></div>
            </section>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <input type="submit" value="Submit" name="submit">
        </div>
    </div>

}
@Scripts.Render("~/Scripts/custom.js")